version: "2"
services:
  image: postgres:13.3
    environment:
      POSTGRES_DB: "couriers_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "habr"
    ports:
      - "2009:5432"
  red:
    image: redis
    ports:
      - "2008:6379"
  web:
    image: myfastapi:latest
    ports:
      - "2007:2007"
    volumes:
      - .:/code