version: "2"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "habr"
      POSTGRES_DB: "my_db"
    ports:
      - "2009:5432"
    volumes:
      - ./db_config_docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  red:
    image: redis
    ports:
      - "2008:6379"
