version: "2"
services:
  web:
    image: my_server:latest
    ports:
      - "2007:2007"
    volumes:
      - .:/code
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "habr"
      POSTGRES_DB: "my_db"
    ports:
      - "2009:5432"
    container_name: "postgres"
    volumes:
      - ./db_config_docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
networks:
  default:
    external:
      name: managing-couriers-network
